version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      - POSTGRES_DB=FastAPI
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
    env_file:
      - .env-non-dev
    ports:
      - 15432:5432
  redis:
    image: redis:7
    container_name: redis
    ports:
      - 6379:6379
  web:
    build:
      context: .
    env_file:
      - .env-non-dev
#    environment:
#      - DATABASE_URL=postgres://postgres:1@postgres:5432/FastAPI
    container_name: fastapi_app
    ports:
      - 8080:8000
    depends_on:
        - postgres
        - redis
    command: ["/fastapi_app/docker/app.sh"]