[tool.pytest.ini_options]
pythonpath = [
  ".", "src",
]
#filterwarnings = [
#    "error",
#    "ignore::MovedIn20Warning:",
#    # note the use of single quote below to denote "raw" strings in TOML
#    'ignore:function ham\(\) is deprecated:DeprecationWarning',
#]
asyncio_mode="auto"